### ISSUE TITLE
Issue with launching OST Overhaul on Fabric 1.19.1

### ISSUE THREAD

**Issue by purejosh** [GlowSand/ostoverhaul#12]
```
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod ostoverhaul
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more

```

**Comment by purejosh** [comment]
It's not much info, but please @ me in discord if you need more info! 

LOVE this mod!

**Comment by purejosh** [comment]
Oh, using `fabric-loader-0.14.8-1.19.1` and `fabric-api-0.58.5+1.19.1`
