### ISSUE TITLE
Error loading class: net/minecraft/class_310 + 1142

### ISSUE THREAD

**Issue by purejosh** [GlowSand/ostoverhaul#13]
```
[22:59:01] [main/WARN]: Error loading class: net/minecraft/class_310 (java.lang.ClassNotFoundException: net/minecraft/class_310)
[22:59:01] [main/WARN]: @Mixin target net.minecraft.class_310 was not found ostOverhaul.mixins.json:MinecraftClientMixin from mod ostoverhaul
[22:59:01] [main/WARN]: Error loading class: net/minecraft/class_1142 (java.lang.ClassNotFoundException: net/minecraft/class_1142)
[22:59:01] [main/WARN]: @Mixin target net.minecraft.class_1142 was not found ostOverhaul.mixins.json:MusicTrackerMixin from mod ostoverhaul
```

Minecraft 1.19.2 with Fabric Loader 0.14.9
ostoverhaul 0.2.6.1

**Comment by purejosh** [comment]
```
[00:56:00] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'ostoverhaul'!
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.9.jar:?]
at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_1813.<init>(int, net.minecraft.class_3414, net.minecraft.class_1792$class_1793)'
at glowsand.ostoverhaul.items.MusicDiscConstructorBecauseItsNotPublic.<init>(MusicDiscConstructorBecauseItsNotPublic.java:8) ~[ostOverhaul-0.2.6.1-1.19.jar:?]
at glowsand.ostoverhaul.OstOverhaul.registerDataStuff(OstOverhaul.java:173) ~[ostOverhaul-0.2.6.1-1.19.jar:?]
at glowsand.ostoverhaul.OstOverhaul.readDataStuff(OstOverhaul.java:129) ~[ostOverhaul-0.2.6.1-1.19.jar:?]
at glowsand.ostoverhaul.OstOverhaul.firstPostInit(OstOverhaul.java:137) ~[ostOverhaul-0.2.6.1-1.19.jar:?]
at glowsand.ostoverhaul.OstOverhaulServer.onInitializeServer(OstOverhaulServer.java:8) ~[ostOverhaul-0.2.6.1-1.19.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
... 7 more
```

**Comment by purejosh** [comment]
```
[01:11:50] [main/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsJsonPrimitive()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[01:11:50] [main/INFO]: [STDERR]: at glowsand.ostoverhaul.OstOverhaul.readDataStuff(OstOverhaul.java:125)
[01:11:50] [main/INFO]: [STDERR]: at glowsand.ostoverhaul.OstOverhaul.firstPostInit(OstOverhaul.java:173)
[01:11:50] [main/INFO]: [STDERR]: at glowsand.ostoverhaul.OstOverhaulServer.onInitializeServer(OstOverhaulServer.java:8)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63)
[01:11:50] [main/INFO]: [STDERR]: at net.minecraft.server.Main.main(Main.java:101)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
[01:11:50] [main/INFO]: [STDERR]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 118 column 6 path $.Discs[0]
[01:11:50] [main/INFO]: [STDERR]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
[01:11:50] [main/INFO]: [STDERR]: at com.google.gson.Gson.fromJson(Gson.java:963)
[01:11:50] [main/INFO]: [STDERR]: at com.google.gson.Gson.fromJson(Gson.java:928)
[01:11:50] [main/INFO]: [STDERR]: at com.google.gson.Gson.fromJson(Gson.java:877)
[01:11:50] [main/INFO]: [STDERR]: at com.google.gson.Gson.fromJson(Gson.java:848)
[01:11:50] [main/INFO]: [STDERR]: at glowsand.ostoverhaul.OstOverhaul.readDataStuff(OstOverhaul.java:160)
[01:11:50] [main/INFO]: [STDERR]: at glowsand.ostoverhaul.OstOverhaul.firstPostInit(OstOverhaul.java:173)
[01:11:50] [main/INFO]: [STDERR]: at glowsand.ostoverhaul.OstOverhaulServer.onInitializeServer(OstOverhaulServer.java:8)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63)
[01:11:50] [main/INFO]: [STDERR]: at net.minecraft.server.Main.main(Main.java:101)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
[01:11:50] [main/INFO]: [STDERR]: at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
[01:11:50] [main/INFO]: [STDERR]: Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 118 column 6 path $.Discs[0]
[01:11:50] [main/INFO]: [STDERR]: at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
[01:11:50] [main/INFO]: [STDERR]: at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
[01:11:50] [main/INFO]: [STDERR]: at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
[01:11:50] [main/INFO]: [STDERR]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
[01:11:50] [main/INFO]: [STDERR]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
[01:11:50] [main/INFO]: [STDERR]: ... 15 more
```
