### ISSUE TITLE
ClassCastException in - 1.18.1 v0.2.3

### ISSUE THREAD

**Issue by squeeglii** [GlowSand/ostoverhaul#5]
Could the latest update please be pushed to this repo? :)
That and this was thrown whilst in a warped forest:

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 15/02/2022, 21:57
Description: Unexpected error

java.lang.ClassCastException: class java.util.HashMap cannot be cast to class com.google.gson.internal.LinkedTreeMap (java.util.HashMap is in module java.base of loader 'bootstrap'; com.google.gson.internal.LinkedTreeMap is in unnamed module of loader 'app')
	at glowsand.ostoverhaul.OstOverhaulConfig.getMusicToPlay(OstOverhaulConfig.java:233)
	at glowsand.ostoverhaul.client.OverhaulMusicTracker.playRandomSound(OverhaulMusicTracker.java:235)
	at glowsand.ostoverhaul.client.OverhaulMusicTracker.playRandomSound(OverhaulMusicTracker.java:230)
	at glowsand.ostoverhaul.client.OverhaulMusicTracker.playMusicOrSmthn(OverhaulMusicTracker.java:200)
	at glowsand.ostoverhaul.client.OverhaulMusicTracker.tick(OverhaulMusicTracker.java:89)
	at net.minecraft.class_1142.handler$zll000$tickmixin(class_1142.java:534)
	at net.minecraft.class_1142.method_18669(class_1142.java)
	at net.minecraft.class_310.method_1574(class_310.java:1759)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by GlowSand** [comment]
Should be fixed in the latest versions 1.18.2 & 1.19 versions
